apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # This is telling the scheduller where NOT TO SCHEDULE the pods, regarding the nodes.
                  # Here, we`re setting it to NOT BE SCHEDULED to a "master" node.`
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values: ["true"]
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  #this is "repelling" the pods from each other.
                  - key: app
                    operator: In
                    values: [myapp]
              #this is to schedule one pod per zone.
              topologyKey: kubernetes.io/hostname #DEPRECATED BUT USED HERE SINCE K3D USES IT YET.
              # topologyKey: topology.kubernetes.io/zone
              # "topology.kubernetes.io/zone" is the new label to be used.
      containers:
        - name: myapp
          image: docker.io/roggoncalves/rotational-goapp:v1.0
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          lifecycle:
            preStop:
              exec:
                command: ["kill", "1"]
      terminationGracePeriodSeconds: 1800
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
